source 'http://rubygems.org'

gem 'json', '~> 1.8', '>= 1.8.3'
gem 'rake'
gem 'rdoc'
gem 'rest-client', '~> 1.8'

group :development do
  gem 'bundler'
  gem 'jeweler'
  gem 'rr'
  gem 'shoulda', '>= 0'
  gem 'simplecov', '>= 0'
end
